### ISSUE TITLE
Add "Send/Use Current Time" Check Box to Message Simulator 

### ISSUE THREAD

**Issue by csmoore** [Esri/vehicle-commander#4]
Add a "Send/Use Current Time" check box to the MessageSimulator to indicate that the simulated time used in messages should be based off the current date-time.

The date/time attribute/tag to be used is "datetimesubmitted" If it exists update it, otherwise add it.

datetimesubmitted = Now()

Another future option (when/if datetimesubmitted is valid/real data): When the simulator starts - the first datetimesubmitted encountered in the xml file = StartTime; then datetimesubmitted = datetimesubmitted - (Start Time) + Now()

**Comment by garys-esri** [comment]
The first part of this issue is resolved in a0b95ce3dff31c714270beb3c2dfe1bd3dadc61e . There is now a list of fields that can be checked on to override those fields' values with the current time in UTC.

I'm punting the second part of this issue. It is sufficiently complex to deserve its own issue, #49, which we can resolve at a later time.

**Comment by csmoore** [comment]
Verified

![image](https://cloud.githubusercontent.com/assets/3090809/6332722/85b1e212-bb55-11e4-9845-52edabe7b03b.png)
