### ISSUE TITLE
ChemLight Buttons Issue

### ISSUE THREAD

**Issue by csmoore** [Esri/vehicle-commander#51]
With the current version, default mapconfig etc. I wasn't able to put a chem light on the map.

I was just running from the ant developer build so not sure if I just need an updated mapconfig.

Here is how I ran:
`vehicle-commander\source\VehicleCommander>ant run`

**Comment by garys-esri** [comment]
I see it too and will have a look.

**Comment by garys-esri** [comment]
I figured it out. The ArcGIS Runtime 10.2.4 MessageProcessor will not display a message of type chemlight if it has no field named sic. It doesn't make sense to me for a chem light to have to have a SIC, but I will 1) adjust Vehicle Commander to add a SIC to make it work (maybe the user's SIC) and 2) report this to Esri Support, since it shouldn't be this way in my opinion.

**Comment by csmoore** [comment]
Verified

![image](https://cloud.githubusercontent.com/assets/3090809/6350357/31e2d004-bc01-11e4-8762-80a9cf96698a.png)
